package com.example.model;

public class Review {

    private int id;         // This will be auto-generated by the database (Auto Increment).
    private int userId;     // Foreign key to the User table
    private String content; // Content of the review
    private int rating;     // Rating of the movie (1-5)
    private int movieId;    // Foreign key to the Movie table
    private Movie movie;    // Associated Movie object (for fetching the movie's details)
    private User user;      // Associated User object (for fetching the user's details)
    private String movie_title;

    // Constructor that initializes the Review object, except for the auto-generated 'id'
    public Review(int userId, String content, int rating, int movieId,String movie_title , Movie movie, User user) {
        this.userId = userId;
        this.content = content;
        this.rating = rating;
        this.movieId = movieId;
        this.movie = movie;
        this.user = user;
        this.movie_title = movie_title;
    }

    // Getters and Setters for the fields
    public int getId() {
        return id;
    }

    public void setId(int id) {
        this.id = id;
    }

    public int getUserId() {
        return userId;
    }

    public String getMovie_title(){
        return movie_title;
    }

    public void setUserId(int userId) {
        this.userId = userId;
    }

    public String getContent() {
        return content;
    }

    public void setContent(String content) {
        this.content = content;
    }

    public int getRating() {
        return rating;
    }

    public void setRating(int rating) {
        this.rating = rating;
    }

    public int getMovieId() {
        return movieId;
    }

    public void setMovieId(int movieId) {
        this.movieId = movieId;
    }

    public Movie getMovie() {
        return movie;
    }

    public void setMovie(Movie movie) {
        this.movie = movie;
    }

    public User getUser() {
        return user;
    }

    public void setUser(User user) {
        this.user = user;
    }

    // Optionally, you can add a toString() method to represent the Review as a string
    @Override
    public String toString() {
        return "Review{" +
                "id=" + id +
                ", userId=" + userId +
                ", content='" + content + '\'' +
                ", rating=" + rating +
                ", movieId=" + movieId +
                '}';
    }
}
